/**
 * Forum RSS — shared type definitions.
 *
 * Covers RSS feed configuration, per-board settings,
 * and feed format preferences.
 */

// ── Feed Configuration ─────────────────────────────────────────────

/** Global RSS feed configuration for a forum. */
export interface RssFeedConfig {
  forum_id: string;
  /** Whether the global forum-wide feed is enabled. */
  global_feed_enabled: boolean;
  /** Default feed format preference. */
  default_format: RssFeedFormat;
  /** Default number of items per feed. */
  items_per_feed: 10 | 25 | 50;
  /** Per-board RSS settings. */
  board_settings: BoardRssSettings[];
  updated_at: string;
}

/** RSS settings for an individual board. */
export interface BoardRssSettings {
  board_id: string;
  board_name: string;
  /** Whether RSS is enabled for this board. */
  rss_enabled: boolean;
  /** Feed URL (generated by backend). */
  feed_url: string;
  /** Atom feed URL (generated by backend). */
  atom_url: string;
  /** Items per feed override (null = use global default). */
  items_per_feed?: 10 | 25 | 50 | null;
}

/** Available RSS feed formats. */
export type RssFeedFormat = 'rss2' | 'atom';

// ── Feed Payloads ──────────────────────────────────────────────────

/** Payload for updating board RSS settings. */
export interface UpdateBoardRssPayload {
  board_id: string;
  rss_enabled: boolean;
  items_per_feed?: 10 | 25 | 50 | null;
}

/** Payload for updating global RSS settings. */
export interface UpdateGlobalRssPayload {
  global_feed_enabled?: boolean;
  default_format?: RssFeedFormat;
  items_per_feed?: 10 | 25 | 50;
}

// ── Feed Item (for client-side parsing) ────────────────────────────

/** A single RSS feed item as parsed on the client. */
export interface RssFeedItem {
  title: string;
  link: string;
  description: string;
  pubDate: string;
  author: string;
  category?: string;
  guid: string;
}

/** Parsed RSS feed response. */
export interface ParsedRssFeed {
  title: string;
  link: string;
  description: string;
  items: RssFeedItem[];
  lastBuildDate: string;
}
