/**
 * Border particle system preset configurations.
 * @module
 */
import type { ParticleType } from '@/types/avatar-borders';
import type { ParticlePreset } from './types';

export const PARTICLE_PRESETS: Record<ParticleType, ParticlePreset> = {
  spark: {
    gravity: 0,
    drag: 0.98,
    minSize: 2,
    maxSize: 4,
    minLife: 0.5,
    maxLife: 1,
    spread: 1,
    initialVelocity: { x: 0, y: 0 },
  },
  flame: {
    gravity: -0.1,
    drag: 0.95,
    minSize: 4,
    maxSize: 8,
    minLife: 0.8,
    maxLife: 1.5,
    spread: 0.3,
    initialVelocity: { x: 0, y: -2 },
  },
  snowflake: {
    gravity: 0.02,
    drag: 0.99,
    minSize: 4,
    maxSize: 8,
    minLife: 3,
    maxLife: 5,
    spread: 0.5,
    initialVelocity: { x: 0, y: 0.5 },
  },
  bubble: {
    gravity: -0.03,
    drag: 0.99,
    minSize: 6,
    maxSize: 12,
    minLife: 2,
    maxLife: 4,
    spread: 0.2,
    initialVelocity: { x: 0, y: -1 },
  },
  sakura: {
    gravity: 0.015,
    drag: 0.995,
    minSize: 6,
    maxSize: 10,
    minLife: 4,
    maxLife: 6,
    spread: 0.8,
    initialVelocity: { x: 0.5, y: 0.3 },
  },
  star: {
    gravity: 0,
    drag: 0.99,
    minSize: 4,
    maxSize: 8,
    minLife: 1,
    maxLife: 2,
    spread: 0.5,
    initialVelocity: { x: 0, y: 0 },
  },
  heart: {
    gravity: -0.02,
    drag: 0.98,
    minSize: 6,
    maxSize: 10,
    minLife: 2,
    maxLife: 3,
    spread: 0.4,
    initialVelocity: { x: 0, y: -1 },
  },
  coin: {
    gravity: 0,
    drag: 0.99,
    minSize: 6,
    maxSize: 10,
    minLife: 2,
    maxLife: 3,
    spread: 0.3,
    initialVelocity: { x: 0, y: 0 },
  },
  leaf: {
    gravity: 0.01,
    drag: 0.995,
    minSize: 5,
    maxSize: 10,
    minLife: 3,
    maxLife: 5,
    spread: 0.6,
    initialVelocity: { x: 0.3, y: 0.2 },
  },
  electric: {
    gravity: 0,
    drag: 0.9,
    minSize: 2,
    maxSize: 12,
    minLife: 0.1,
    maxLife: 0.3,
    spread: 0.8,
    initialVelocity: { x: 0, y: 0 },
  },
  rune: {
    gravity: 0,
    drag: 0.99,
    minSize: 8,
    maxSize: 12,
    minLife: 2,
    maxLife: 4,
    spread: 0.2,
    initialVelocity: { x: 0, y: 0 },
  },
  crystal: {
    gravity: 0,
    drag: 0.98,
    minSize: 4,
    maxSize: 10,
    minLife: 1.5,
    maxLife: 3,
    spread: 0.3,
    initialVelocity: { x: 0, y: 0 },
  },
  gear: {
    gravity: 0,
    drag: 0.995,
    minSize: 8,
    maxSize: 14,
    minLife: 3,
    maxLife: 5,
    spread: 0.2,
    initialVelocity: { x: 0, y: 0 },
  },
  pixel: {
    gravity: 0,
    drag: 0.98,
    minSize: 3,
    maxSize: 5,
    minLife: 0.5,
    maxLife: 1,
    spread: 0.5,
    initialVelocity: { x: 0, y: 0 },
  },
  glitch: {
    gravity: 0,
    drag: 0.9,
    minSize: 8,
    maxSize: 20,
    minLife: 0.1,
    maxLife: 0.2,
    spread: 1,
    initialVelocity: { x: 0, y: 0 },
  },
  void: {
    gravity: 0,
    drag: 0.99,
    minSize: 3,
    maxSize: 8,
    minLife: 1,
    maxLife: 2,
    spread: 0.6,
    initialVelocity: { x: 0, y: 0 },
  },
  circle: {
    gravity: 0,
    drag: 0.98,
    minSize: 4,
    maxSize: 10,
    minLife: 1,
    maxLife: 2,
    spread: 0.5,
    initialVelocity: { x: 0, y: 0 },
  },
  square: {
    gravity: 0,
    drag: 0.97,
    minSize: 4,
    maxSize: 8,
    minLife: 1,
    maxLife: 2,
    spread: 0.4,
    initialVelocity: { x: 0, y: 0 },
  },
  sparkle: {
    gravity: 0,
    drag: 0.98,
    minSize: 3,
    maxSize: 6,
    minLife: 0.5,
    maxLife: 1.5,
    spread: 0.6,
    initialVelocity: { x: 0, y: 0 },
  },
  petal: {
    gravity: 0.01,
    drag: 0.995,
    minSize: 5,
    maxSize: 10,
    minLife: 3,
    maxLife: 5,
    spread: 0.7,
    initialVelocity: { x: 0.4, y: 0.2 },
  },
  lightning: {
    gravity: 0,
    drag: 0.85,
    minSize: 2,
    maxSize: 15,
    minLife: 0.05,
    maxLife: 0.15,
    spread: 1,
    initialVelocity: { x: 0, y: 0 },
  },
  triangle: {
    gravity: 0,
    drag: 0.98,
    minSize: 5,
    maxSize: 10,
    minLife: 1.5,
    maxLife: 2.5,
    spread: 0.4,
    initialVelocity: { x: 0, y: 0 },
  },
  hexagon: {
    gravity: 0,
    drag: 0.98,
    minSize: 6,
    maxSize: 12,
    minLife: 2,
    maxLife: 3,
    spread: 0.3,
    initialVelocity: { x: 0, y: 0 },
  },
  custom: {
    gravity: 0,
    drag: 0.98,
    minSize: 4,
    maxSize: 10,
    minLife: 1,
    maxLife: 2,
    spread: 0.5,
    initialVelocity: { x: 0, y: 0 },
  },
};
