/**
 * Animation Presets - Shared entering/exiting/layout animation preset maps
 *
 * Used by AnimatedView, AnimatedText, AnimatedList, AnimatedImage, and other
 * animated components to resolve string preset keys to Reanimated animations.
 */

import {
  FadeIn,
  FadeOut,
  FadeInUp,
  FadeInDown,
  FadeInLeft,
  FadeInRight,
  FadeOutUp,
  FadeOutDown,
  FadeOutLeft,
  FadeOutRight,
  SlideInUp,
  SlideInDown,
  SlideInLeft,
  SlideInRight,
  SlideOutUp,
  SlideOutDown,
  SlideOutLeft,
  SlideOutRight,
  ZoomIn,
  ZoomOut,
  BounceIn,
  BounceOut,
  FlipInXUp,
  FlipInXDown,
  FlipInYLeft,
  FlipInYRight,
  FlipOutXUp,
  FlipOutXDown,
  FlipOutYLeft,
  FlipOutYRight,
  RotateInDownLeft,
  RotateInDownRight,
  RotateInUpLeft,
  RotateInUpRight,
  RotateOutDownLeft,
  RotateOutDownRight,
  RotateOutUpLeft,
  RotateOutUpRight,
  Layout,
  LinearTransition,
  SequencedTransition,
  FadingTransition,
  JumpingTransition,
  CurvedTransition,
  EntryExitTransition,
} from 'react-native-reanimated';

export const ENTERING_PRESETS = {
  fadeIn: FadeIn,
  fadeInUp: FadeInUp,
  fadeInDown: FadeInDown,
  fadeInLeft: FadeInLeft,
  fadeInRight: FadeInRight,
  slideInUp: SlideInUp,
  slideInDown: SlideInDown,
  slideInLeft: SlideInLeft,
  slideInRight: SlideInRight,
  zoomIn: ZoomIn,
  bounceIn: BounceIn,
  flipInXUp: FlipInXUp,
  flipInXDown: FlipInXDown,
  flipInYLeft: FlipInYLeft,
  flipInYRight: FlipInYRight,
  rotateInDownLeft: RotateInDownLeft,
  rotateInDownRight: RotateInDownRight,
  rotateInUpLeft: RotateInUpLeft,
  rotateInUpRight: RotateInUpRight,
};

export const EXITING_PRESETS = {
  fadeOut: FadeOut,
  fadeOutUp: FadeOutUp,
  fadeOutDown: FadeOutDown,
  fadeOutLeft: FadeOutLeft,
  fadeOutRight: FadeOutRight,
  slideOutUp: SlideOutUp,
  slideOutDown: SlideOutDown,
  slideOutLeft: SlideOutLeft,
  slideOutRight: SlideOutRight,
  zoomOut: ZoomOut,
  bounceOut: BounceOut,
  flipOutXUp: FlipOutXUp,
  flipOutXDown: FlipOutXDown,
  flipOutYLeft: FlipOutYLeft,
  flipOutYRight: FlipOutYRight,
  rotateOutDownLeft: RotateOutDownLeft,
  rotateOutDownRight: RotateOutDownRight,
  rotateOutUpLeft: RotateOutUpLeft,
  rotateOutUpRight: RotateOutUpRight,
};

export const LAYOUT_PRESETS = {
  default: Layout,
  linear: LinearTransition,
  sequenced: SequencedTransition,
  fading: FadingTransition,
  jumping: JumpingTransition,
  curved: CurvedTransition,
  entryExit: EntryExitTransition,
};
