/**
 * Theme constants and mock data
 * @module pages/customize/theme-customization
 */

import type { Theme } from './types';

export const MOCK_THEMES: Theme[] = [
  // Profile Themes
  {
    id: 'profile-default',
    name: 'Classic Purple',
    description: 'Default CGraph purple theme',
    category: 'profile',
    colors: {
      primary: '#8B5CF6',
      secondary: '#A78BFA',
      accent: '#C084FC',
      background: '#1F1F23',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #8B5CF6, #A78BFA)',
    unlocked: true,
  },
  {
    id: 'profile-ocean',
    name: 'Ocean Blue',
    description: 'Calming blue ocean theme',
    category: 'profile',
    colors: {
      primary: '#0EA5E9',
      secondary: '#38BDF8',
      accent: '#7DD3FC',
      background: '#0C1E2E',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #0EA5E9, #38BDF8)',
    unlocked: true,
  },
  {
    id: 'profile-forest',
    name: 'Forest Green',
    description: 'Natural green forest theme',
    category: 'profile',
    colors: {
      primary: '#10B981',
      secondary: '#34D399',
      accent: '#6EE7B7',
      background: '#0F2419',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #10B981, #34D399)',
    unlocked: true,
  },
  {
    id: 'profile-sunset',
    name: 'Sunset Orange',
    description: 'Warm sunset gradient',
    category: 'profile',
    colors: {
      primary: '#F97316',
      secondary: '#FB923C',
      accent: '#FDBA74',
      background: '#2C1810',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #F97316, #FB923C)',
    unlocked: false,
    unlockRequirement: 'Reach Level 15',
  },
  {
    id: 'profile-midnight',
    name: 'Midnight Purple',
    description: 'Deep purple night theme',
    category: 'profile',
    colors: {
      primary: '#7C3AED',
      secondary: '#9333EA',
      accent: '#A855F7',
      background: '#1E1034',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #7C3AED, #9333EA)',
    unlocked: false,
    unlockRequirement: 'Complete 25 Quests',
  },
  {
    id: 'profile-cherry',
    name: 'Cherry Blossom',
    description: 'Soft pink cherry theme',
    category: 'profile',
    colors: {
      primary: '#EC4899',
      secondary: '#F472B6',
      accent: '#F9A8D4',
      background: '#2E1020',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #EC4899, #F472B6)',
    unlocked: true,
  },

  // Chat Themes
  {
    id: 'chat-default',
    name: 'Default Bubbles',
    description: 'Classic chat bubble style',
    category: 'chat',
    colors: {
      primary: '#8B5CF6',
      secondary: '#374151',
      accent: '#A78BFA',
      background: '#111111',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #8B5CF6, #374151)',
    unlocked: true,
  },
  {
    id: 'chat-indigo',
    name: 'Indigo Dark',
    description: 'Deep indigo dark theme',
    category: 'chat',
    colors: {
      primary: '#5865F2',
      secondary: '#2C2F33',
      accent: '#7289DA',
      background: '#23272A',
      text: '#DCDDDE',
    },
    preview: 'linear-gradient(135deg, #5865F2, #2C2F33)',
    unlocked: true,
  },
  {
    id: 'chat-sky',
    name: 'Sky Blue',
    description: 'Light sky blue theme',
    category: 'chat',
    colors: {
      primary: '#0088CC',
      secondary: '#FFFFFF',
      accent: '#54A9EB',
      background: '#FFFFFF',
      text: '#000000',
    },
    preview: 'linear-gradient(135deg, #0088CC, #54A9EB)',
    unlocked: true,
  },
  {
    id: 'chat-neon',
    name: 'Neon Glow',
    description: 'Cyberpunk neon theme',
    category: 'chat',
    colors: {
      primary: '#FF006E',
      secondary: '#8338EC',
      accent: '#3A86FF',
      background: '#0A0014',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #FF006E, #8338EC, #3A86FF)',
    unlocked: false,
    unlockRequirement: 'Reach Level 20',
    isPremium: true,
  },
  {
    id: 'chat-minimal',
    name: 'Minimal White',
    description: 'Clean minimalist theme',
    category: 'chat',
    colors: {
      primary: '#000000',
      secondary: '#F3F4F6',
      accent: '#6B7280',
      background: '#FFFFFF',
      text: '#111827',
    },
    preview: 'linear-gradient(135deg, #F3F4F6, #E5E7EB)',
    unlocked: true,
  },

  // Forum Themes
  {
    id: 'forum-default',
    name: 'Classic Forum',
    description: 'Traditional forum layout',
    category: 'forum',
    colors: {
      primary: '#8B5CF6',
      secondary: '#1F2937',
      accent: '#A78BFA',
      background: '#111111',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #8B5CF6, #1F2937)',
    unlocked: true,
  },
  {
    id: 'forum-classic',
    name: 'Classic Style',
    description: 'Classic forum layout',
    category: 'forum',
    colors: {
      primary: '#FF4500',
      secondary: '#1A1A1B',
      accent: '#FF5700',
      background: '#0B0B0C',
      text: '#D7DADC',
    },
    preview: 'linear-gradient(135deg, #FF4500, #1A1A1B)',
    unlocked: true,
  },
  {
    id: 'forum-hacker',
    name: 'Hacker News',
    description: 'HN minimalist style',
    category: 'forum',
    colors: {
      primary: '#FF6600',
      secondary: '#F6F6EF',
      accent: '#828282',
      background: '#F6F6EF',
      text: '#000000',
    },
    preview: 'linear-gradient(135deg, #FF6600, #F6F6EF)',
    unlocked: false,
    unlockRequirement: 'Create 50 Posts',
  },
  {
    id: 'forum-gaming',
    name: 'Gaming RGB',
    description: 'RGB gaming aesthetic',
    category: 'forum',
    colors: {
      primary: '#FF0080',
      secondary: '#7928CA',
      accent: '#00DFD8',
      background: '#0A0A0F',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #FF0080, #7928CA, #00DFD8)',
    unlocked: false,
    unlockRequirement: 'Join 10 Forums',
    isPremium: true,
  },

  // App Themes
  {
    id: 'app-dark',
    name: 'Dark Mode',
    description: 'Default dark theme',
    category: 'app',
    colors: {
      primary: '#8B5CF6',
      secondary: '#1F1F23',
      accent: '#A78BFA',
      background: '#0F0F11',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #0F0F11, #1F1F23)',
    unlocked: true,
  },
  {
    id: 'app-light',
    name: 'Light Mode',
    description: 'Clean light theme',
    category: 'app',
    colors: {
      primary: '#8B5CF6',
      secondary: '#F9FAFB',
      accent: '#A78BFA',
      background: '#FFFFFF',
      text: '#111827',
    },
    preview: 'linear-gradient(135deg, #FFFFFF, #F9FAFB)',
    unlocked: true,
  },
  {
    id: 'app-amoled',
    name: 'AMOLED Black',
    description: 'True black for OLED',
    category: 'app',
    colors: {
      primary: '#8B5CF6',
      secondary: '#000000',
      accent: '#A78BFA',
      background: '#000000',
      text: '#FFFFFF',
    },
    preview: 'linear-gradient(135deg, #000000, #1a1a1a)',
    unlocked: false,
    unlockRequirement: 'Premium Tier',
    isPremium: true,
  },
  {
    id: 'app-nord',
    name: 'Nord Theme',
    description: 'Arctic-inspired colors',
    category: 'app',
    colors: {
      primary: '#88C0D0',
      secondary: '#2E3440',
      accent: '#8FBCBB',
      background: '#2E3440',
      text: '#ECEFF4',
    },
    preview: 'linear-gradient(135deg, #88C0D0, #2E3440)',
    unlocked: false,
    unlockRequirement: 'Reach Level 30',
  },
];
