/**
 * Constants and mock data for effects customization
 * @module pages/customize/effects-customization
 */

import type { ParticleEffect, BackgroundEffect, AnimationSet } from './types';

export const PARTICLE_EFFECTS: ParticleEffect[] = [
  {
    id: 'particle-none',
    name: 'None',
    description: 'No particle effects',
    type: 'none',
    density: 'low',
    performance: 'light',
    unlocked: true,
  },
  {
    id: 'particle-snow',
    name: 'Falling Snow',
    description: 'Gentle snowflakes falling',
    type: 'snow',
    density: 'medium',
    performance: 'light',
    unlocked: true,
  },
  {
    id: 'particle-confetti',
    name: 'Confetti',
    description: 'Celebratory confetti burst',
    type: 'confetti',
    density: 'high',
    performance: 'medium',
    unlocked: true,
  },
  {
    id: 'particle-stars',
    name: 'Twinkling Stars',
    description: 'Starfield background',
    type: 'stars',
    density: 'medium',
    performance: 'light',
    unlocked: true,
  },
  {
    id: 'particle-fireflies',
    name: 'Fireflies',
    description: 'Glowing fireflies floating',
    type: 'fireflies',
    density: 'low',
    performance: 'medium',
    unlocked: false,
    unlockRequirement: 'Reach Level 10',
  },
  {
    id: 'particle-bubbles',
    name: 'Rising Bubbles',
    description: 'Bubbles floating upward',
    type: 'bubbles',
    density: 'medium',
    performance: 'light',
    unlocked: true,
  },
  {
    id: 'particle-sakura',
    name: 'Cherry Blossoms',
    description: 'Sakura petals falling',
    type: 'sakura',
    density: 'medium',
    performance: 'medium',
    unlocked: false,
    unlockRequirement: 'Complete Spring Event',
  },
  {
    id: 'particle-matrix',
    name: 'Matrix Rain',
    description: 'Digital matrix code rain',
    type: 'matrix',
    density: 'high',
    performance: 'heavy',
    unlocked: false,
    unlockRequirement: 'Reach Level 25',
    isPremium: true,
  },
  {
    id: 'particle-sparkles',
    name: 'Magic Sparkles',
    description: 'Magical sparkle effects',
    type: 'sparkles',
    density: 'medium',
    performance: 'medium',
    unlocked: false,
    unlockRequirement: 'Premium Tier',
    isPremium: true,
  },
  {
    id: 'particle-flames',
    name: 'Rising Flames',
    description: 'Fire particles rising',
    type: 'flames',
    density: 'high',
    performance: 'heavy',
    unlocked: false,
    unlockRequirement: 'Win 50 PvP Matches',
  },
  {
    id: 'particle-leaves',
    name: 'Autumn Leaves',
    description: 'Falling autumn leaves',
    type: 'leaves',
    density: 'medium',
    performance: 'light',
    unlocked: false,
    unlockRequirement: 'Complete Fall Event',
  },
  {
    id: 'particle-hearts',
    name: 'Floating Hearts',
    description: 'Love-themed hearts',
    type: 'hearts',
    density: 'low',
    performance: 'light',
    unlocked: false,
    unlockRequirement: "Valentine's Event",
  },
];

export const BACKGROUND_EFFECTS: BackgroundEffect[] = [
  {
    id: 'bg-none',
    name: 'None',
    description: 'No background effect',
    preview: '#0F0F11',
    animated: false,
    performance: 'light',
    unlocked: true,
  },
  {
    id: 'bg-static',
    name: 'Static',
    description: 'Subtle static gradient background',
    preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    animated: false,
    performance: 'light',
    unlocked: true,
  },
  {
    id: 'bg-animated',
    name: 'Animated',
    description: 'Flowing animated gradient background',
    preview: 'linear-gradient(135deg, #667eea, #764ba2, #f093fb)',
    animated: true,
    performance: 'medium',
    unlocked: true,
  },
];

export const ANIMATION_SETS: AnimationSet[] = [
  {
    id: 'anim-instant',
    name: 'Instant',
    description: 'No animations, instant transitions',
    speed: 'instant',
    easing: 'linear',
    unlocked: true,
  },
  {
    id: 'anim-fast',
    name: 'Fast & Snappy',
    description: 'Quick 150ms animations',
    speed: 'fast',
    easing: 'ease-out',
    unlocked: true,
  },
  {
    id: 'anim-normal',
    name: 'Normal',
    description: 'Balanced 250ms animations',
    speed: 'normal',
    easing: 'ease-in-out',
    unlocked: true,
  },
  {
    id: 'anim-smooth',
    name: 'Smooth',
    description: 'Polished 350ms animations',
    speed: 'smooth',
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    unlocked: true,
  },
  {
    id: 'anim-bouncy',
    name: 'Bouncy',
    description: 'Spring physics with bounce',
    speed: 'normal',
    easing: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
    unlocked: false,
    unlockRequirement: 'Reach Level 10',
  },
  {
    id: 'anim-elastic',
    name: 'Elastic',
    description: 'Elastic overshoot effect',
    speed: 'smooth',
    easing: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    unlocked: false,
    unlockRequirement: 'Reach Level 15',
  },
  {
    id: 'anim-cinematic',
    name: 'Cinematic',
    description: 'Slow dramatic 500ms',
    speed: 'slow',
    easing: 'cubic-bezier(0.22, 1, 0.36, 1)',
    unlocked: false,
    unlockRequirement: 'Premium Tier',
  },
  {
    id: 'anim-gaming',
    name: 'Gaming',
    description: 'Ultra-fast 100ms for gaming',
    speed: 'fast',
    easing: 'linear',
    unlocked: false,
    unlockRequirement: 'Win 100 PvP Matches',
  },
];
