defmodule CGraphWeb.Plugs.CorrelationId do
  @moduledoc """
  Ensures every request has a correlation ID for tracing across services.

  - Reuses incoming "x-correlation-id" if present; otherwise falls back to the
    request ID generated by Plug.RequestId.
  - Adds the correlation ID to response headers and logger metadata.
  """

  import Plug.Conn
  require Logger

  @header "x-correlation-id"

  def init(opts), do: opts

  def call(conn, _opts) do
    correlation_id =
      conn
      |> get_req_header(@header)
      |> List.first()
      |> case do
        nil -> get_req_id(conn)
        "" -> get_req_id(conn)
        id -> id
      end

    Logger.metadata(correlation_id: correlation_id)

    conn
    |> put_resp_header(@header, correlation_id)
    |> assign(:correlation_id, correlation_id)
  end

  defp get_req_id(conn) do
    # Plug.RequestId sets the header; reuse if present, else generate a short ID.
    case get_resp_header(conn, "x-request-id") do
      [id | _] -> id
      _ -> "corr-" <> Base.encode16(:crypto.strong_rand_bytes(8), case: :lower)
    end
  end
end
