# Seed: 70 badges matching COSMETICS_MANIFEST.json rarity distribution
# free: 10, common: 15, uncommon: 15, rare: 12, epic: 8, legendary: 6, mythic: 4
#
# Idempotent — uses Repo.insert_all with on_conflict: :nothing (conflict on slug).
#
# Usage:
#   mix run priv/repo/seeds/badge_seeds.exs

alias Cgraph.Repo

now = DateTime.utc_now() |> DateTime.truncate(:microsecond)

badges =
  [
    # ─── FREE (10) ───
    %{slug: "newcomer", name: "Newcomer", description: "Welcome to the community!", icon_url: "/images/badges/newcomer.png", rarity: "free", category: "social", track: "onboarding", unlock_type: "default", unlock_condition: %{"description" => "Account created"}, nodes_cost: 0},
    %{slug: "first-message", name: "First Message", description: "You sent your very first message.", icon_url: "/images/badges/first-message.png", rarity: "free", category: "social", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Send first message"}, nodes_cost: 0},
    %{slug: "first-friend", name: "First Friend", description: "You made your first connection.", icon_url: "/images/badges/first-friend.png", rarity: "free", category: "social", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Add first friend"}, nodes_cost: 0},
    %{slug: "profile-complete", name: "Profile Complete", description: "Your profile is fully set up.", icon_url: "/images/badges/profile-complete.png", rarity: "free", category: "social", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Complete profile setup"}, nodes_cost: 0},
    %{slug: "first-post", name: "First Post", description: "You created your first forum post.", icon_url: "/images/badges/first-post.png", rarity: "free", category: "social", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Create first forum post"}, nodes_cost: 0},
    %{slug: "explorer", name: "Explorer", description: "You've explored different sections of the platform.", icon_url: "/images/badges/explorer.png", rarity: "free", category: "social", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Visit 5 different sections"}, nodes_cost: 0},
    %{slug: "early-adopter", name: "Early Adopter", description: "Joined during the beta period.", icon_url: "/images/badges/early-adopter.png", rarity: "free", category: "meta", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Join during beta period"}, nodes_cost: 0},
    %{slug: "verified-email", name: "Verified Email", description: "Your email address is verified.", icon_url: "/images/badges/verified-email.png", rarity: "free", category: "security", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Verify email address"}, nodes_cost: 0},
    %{slug: "two-factor", name: "Two-Factor Guardian", description: "You enabled two-factor authentication.", icon_url: "/images/badges/two-factor.png", rarity: "free", category: "security", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Enable 2FA"}, nodes_cost: 0},
    %{slug: "avatar-set", name: "Avatar Set", description: "You uploaded a custom avatar.", icon_url: "/images/badges/avatar-set.png", rarity: "free", category: "social", track: "onboarding", unlock_type: "achievement", unlock_condition: %{"description" => "Upload avatar"}, nodes_cost: 0},

    # ─── COMMON (15) ───
    %{slug: "chatterbox", name: "Chatterbox", description: "Sent 100 messages across the platform.", icon_url: "/images/badges/chatterbox.png", rarity: "common", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Send 100 messages"}, nodes_cost: 0},
    %{slug: "social-butterfly", name: "Social Butterfly", description: "Added 10 friends to your network.", icon_url: "/images/badges/social-butterfly.png", rarity: "common", category: "social", track: "social", unlock_type: "achievement", unlock_condition: %{"description" => "Add 10 friends"}, nodes_cost: 0},
    %{slug: "night-owl", name: "Night Owl", description: "Active after midnight 10 times.", icon_url: "/images/badges/night-owl.png", rarity: "common", category: "social", track: "activity", unlock_type: "achievement", unlock_condition: %{"description" => "Active after midnight 10 times"}, nodes_cost: 0},
    %{slug: "early-bird", name: "Early Bird", description: "Active before 7am 10 times.", icon_url: "/images/badges/early-bird.png", rarity: "common", category: "social", track: "activity", unlock_type: "achievement", unlock_condition: %{"description" => "Active before 7am 10 times"}, nodes_cost: 0},
    %{slug: "thread-starter", name: "Thread Starter", description: "Created 5 forum threads.", icon_url: "/images/badges/thread-starter.png", rarity: "common", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Create 5 forum threads"}, nodes_cost: 0},
    %{slug: "helpful-reply", name: "Helpful Reply", description: "Received 5 upvoted replies.", icon_url: "/images/badges/helpful-reply.png", rarity: "common", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Get 5 upvoted replies"}, nodes_cost: 0},
    %{slug: "group-joiner", name: "Group Joiner", description: "Joined 3 groups.", icon_url: "/images/badges/group-joiner.png", rarity: "common", category: "social", track: "groups", unlock_type: "achievement", unlock_condition: %{"description" => "Join 3 groups"}, nodes_cost: 0},
    %{slug: "emoji-fan", name: "Emoji Fan", description: "Used 50 emojis in messages.", icon_url: "/images/badges/emoji-fan.png", rarity: "common", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Use 50 emojis"}, nodes_cost: 0},
    %{slug: "streak-starter", name: "Streak Starter", description: "Achieved a 3-day login streak.", icon_url: "/images/badges/streak-starter.png", rarity: "common", category: "social", track: "activity", unlock_type: "achievement", unlock_condition: %{"description" => "3-day login streak"}, nodes_cost: 0},
    %{slug: "voice-debut", name: "Voice Debut", description: "Joined your first voice call.", icon_url: "/images/badges/voice-debut.png", rarity: "common", category: "social", track: "voice", unlock_type: "achievement", unlock_condition: %{"description" => "Join first voice call"}, nodes_cost: 0},
    %{slug: "file-sharer", name: "File Sharer", description: "Shared 10 files with others.", icon_url: "/images/badges/file-sharer.png", rarity: "common", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Share 10 files"}, nodes_cost: 0},
    %{slug: "reactor", name: "Reactor", description: "Added 50 reactions to messages.", icon_url: "/images/badges/reactor.png", rarity: "common", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Add 50 reactions"}, nodes_cost: 0},
    %{slug: "poll-voter", name: "Poll Voter", description: "Voted in 10 polls.", icon_url: "/images/badges/poll-voter.png", rarity: "common", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Vote in 10 polls"}, nodes_cost: 0},
    %{slug: "bookworm", name: "Bookworm", description: "Read 50 forum threads.", icon_url: "/images/badges/bookworm.png", rarity: "common", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Read 50 threads"}, nodes_cost: 0},
    %{slug: "customizer", name: "Customizer", description: "Changed your theme 5 times.", icon_url: "/images/badges/customizer.png", rarity: "common", category: "social", track: "customization", unlock_type: "achievement", unlock_condition: %{"description" => "Change theme 5 times"}, nodes_cost: 0},

    # ─── UNCOMMON (15) ───
    %{slug: "conversationalist", name: "Conversationalist", description: "Sent 500 messages across the platform.", icon_url: "/images/badges/conversationalist.png", rarity: "uncommon", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Send 500 messages"}, nodes_cost: 0},
    %{slug: "community-pillar", name: "Community Pillar", description: "Added 25 friends to your network.", icon_url: "/images/badges/community-pillar.png", rarity: "uncommon", category: "social", track: "social", unlock_type: "achievement", unlock_condition: %{"description" => "Add 25 friends"}, nodes_cost: 0},
    %{slug: "forum-regular", name: "Forum Regular", description: "Posted 25 times in the forums.", icon_url: "/images/badges/forum-regular.png", rarity: "uncommon", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Post 25 times in forums"}, nodes_cost: 0},
    %{slug: "streak-keeper", name: "Streak Keeper", description: "Maintained a 7-day login streak.", icon_url: "/images/badges/streak-keeper.png", rarity: "uncommon", category: "social", track: "activity", unlock_type: "achievement", unlock_condition: %{"description" => "7-day login streak"}, nodes_cost: 0},
    %{slug: "group-leader", name: "Group Leader", description: "Created your own group.", icon_url: "/images/badges/group-leader.png", rarity: "uncommon", category: "social", track: "groups", unlock_type: "achievement", unlock_condition: %{"description" => "Create a group"}, nodes_cost: 0},
    %{slug: "voice-regular", name: "Voice Regular", description: "Spent 10 hours in voice calls.", icon_url: "/images/badges/voice-regular.png", rarity: "uncommon", category: "social", track: "voice", unlock_type: "achievement", unlock_condition: %{"description" => "10 hours in voice calls"}, nodes_cost: 0},
    %{slug: "media-maven", name: "Media Maven", description: "Shared 50 media files.", icon_url: "/images/badges/media-maven.png", rarity: "uncommon", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Share 50 media files"}, nodes_cost: 0},
    %{slug: "poll-creator", name: "Poll Creator", description: "Created 5 polls.", icon_url: "/images/badges/poll-creator.png", rarity: "uncommon", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Create 5 polls"}, nodes_cost: 0},
    %{slug: "mentor", name: "Mentor", description: "Helped 10 new users find their way.", icon_url: "/images/badges/mentor.png", rarity: "uncommon", category: "social", track: "social", unlock_type: "achievement", unlock_condition: %{"description" => "Help 10 new users"}, nodes_cost: 0},
    %{slug: "event-attendee", name: "Event Attendee", description: "Attended 3 community events.", icon_url: "/images/badges/event-attendee.png", rarity: "uncommon", category: "social", track: "events", unlock_type: "achievement", unlock_condition: %{"description" => "Attend 3 events"}, nodes_cost: 0},
    %{slug: "bug-reporter", name: "Bug Reporter", description: "Reported 3 bugs to help improve the platform.", icon_url: "/images/badges/bug-reporter.png", rarity: "uncommon", category: "social", track: "contribution", unlock_type: "achievement", unlock_condition: %{"description" => "Report 3 bugs"}, nodes_cost: 0},
    %{slug: "top-contributor", name: "Top Contributor", description: "Received 50 upvotes on your posts.", icon_url: "/images/badges/top-contributor.png", rarity: "uncommon", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Get 50 upvotes on posts"}, nodes_cost: 0},
    %{slug: "gif-master", name: "GIF Master", description: "Sent 100 GIFs in conversations.", icon_url: "/images/badges/gif-master.png", rarity: "uncommon", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Send 100 GIFs"}, nodes_cost: 0},
    %{slug: "sticker-collector", name: "Sticker Collector", description: "Collected 20 unique stickers.", icon_url: "/images/badges/sticker-collector.png", rarity: "uncommon", category: "social", track: "customization", unlock_type: "achievement", unlock_condition: %{"description" => "Collect 20 stickers"}, nodes_cost: 0},
    %{slug: "calendar-keeper", name: "Calendar Keeper", description: "Created 10 calendar events.", icon_url: "/images/badges/calendar-keeper.png", rarity: "uncommon", category: "social", track: "activity", unlock_type: "achievement", unlock_condition: %{"description" => "Create 10 calendar events"}, nodes_cost: 0},

    # ─── RARE (12) ───
    %{slug: "debate-champion", name: "Debate Champion", description: "Won 5 forum debates.", icon_url: "/images/badges/debate-champion.png", rarity: "rare", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Win 5 forum debates"}, nodes_cost: 0},
    %{slug: "marathon-chatter", name: "Marathon Chatter", description: "Sent 2000 messages across the platform.", icon_url: "/images/badges/marathon-chatter.png", rarity: "rare", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Send 2000 messages"}, nodes_cost: 0},
    %{slug: "streak-master", name: "Streak Master", description: "Maintained a 30-day login streak.", icon_url: "/images/badges/streak-master.png", rarity: "rare", category: "social", track: "activity", unlock_type: "achievement", unlock_condition: %{"description" => "30-day login streak"}, nodes_cost: 0},
    %{slug: "voice-veteran", name: "Voice Veteran", description: "Spent 50 hours in voice calls.", icon_url: "/images/badges/voice-veteran.png", rarity: "rare", category: "social", track: "voice", unlock_type: "achievement", unlock_condition: %{"description" => "50 hours in voice calls"}, nodes_cost: 0},
    %{slug: "community-builder", name: "Community Builder", description: "Grew a group to 50 members.", icon_url: "/images/badges/community-builder.png", rarity: "rare", category: "social", track: "groups", unlock_type: "achievement", unlock_condition: %{"description" => "Grow group to 50 members"}, nodes_cost: 0},
    %{slug: "forum-sage", name: "Forum Sage", description: "Posted 100 forum replies.", icon_url: "/images/badges/forum-sage.png", rarity: "rare", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Post 100 forum replies"}, nodes_cost: 0},
    %{slug: "event-organizer", name: "Event Organizer", description: "Organized 5 community events.", icon_url: "/images/badges/event-organizer.png", rarity: "rare", category: "social", track: "events", unlock_type: "achievement", unlock_condition: %{"description" => "Organize 5 events"}, nodes_cost: 0},
    %{slug: "crypto-pioneer", name: "Crypto Pioneer", description: "Set up end-to-end encrypted conversations.", icon_url: "/images/badges/crypto-pioneer.png", rarity: "rare", category: "social", track: "crypto", unlock_type: "achievement", unlock_condition: %{"description" => "Set up E2EE conversations"}, nodes_cost: 0},
    %{slug: "polyglot", name: "Polyglot", description: "Chatted in 5 different languages.", icon_url: "/images/badges/polyglot.png", rarity: "rare", category: "social", track: "messaging", unlock_type: "achievement", unlock_condition: %{"description" => "Chat in 5 languages"}, nodes_cost: 0},
    %{slug: "wiki-editor", name: "Wiki Editor", description: "Edited 20 wiki pages.", icon_url: "/images/badges/wiki-editor.png", rarity: "rare", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Edit 20 wiki pages"}, nodes_cost: 0},
    %{slug: "trending-poster", name: "Trending Poster", description: "Created a trending post.", icon_url: "/images/badges/trending-poster.png", rarity: "rare", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Get a trending post"}, nodes_cost: 0},
    %{slug: "connector", name: "Connector", description: "Introduced 10 users to each other.", icon_url: "/images/badges/connector.png", rarity: "rare", category: "social", track: "social", unlock_type: "achievement", unlock_condition: %{"description" => "Introduce 10 users to each other"}, nodes_cost: 0},

    # ─── EPIC (8) ───
    %{slug: "influencer", name: "Influencer", description: "Amassed 100 friends on the platform.", icon_url: "/images/badges/influencer.png", rarity: "epic", category: "social", track: "social", unlock_type: "achievement", unlock_condition: %{"description" => "Have 100 friends"}, nodes_cost: 0},
    %{slug: "forum-legend", name: "Forum Legend", description: "Posted 500 forum messages.", icon_url: "/images/badges/forum-legend.png", rarity: "epic", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "Post 500 forum messages"}, nodes_cost: 0},
    %{slug: "streak-legend", name: "Streak Legend", description: "Maintained a 90-day login streak.", icon_url: "/images/badges/streak-legend.png", rarity: "epic", category: "social", track: "activity", unlock_type: "achievement", unlock_condition: %{"description" => "90-day login streak"}, nodes_cost: 0},
    %{slug: "voice-star", name: "Voice Star", description: "Spent 200 hours in voice calls.", icon_url: "/images/badges/voice-star.png", rarity: "epic", category: "social", track: "voice", unlock_type: "achievement", unlock_condition: %{"description" => "200 hours in voice calls"}, nodes_cost: 0},
    %{slug: "event-legend", name: "Event Legend", description: "Organized 25 community events.", icon_url: "/images/badges/event-legend.png", rarity: "epic", category: "social", track: "events", unlock_type: "achievement", unlock_condition: %{"description" => "Organize 25 events"}, nodes_cost: 0},
    %{slug: "security-guru", name: "Security Guru", description: "Completed a full security audit.", icon_url: "/images/badges/security-guru.png", rarity: "epic", category: "social", track: "security", unlock_type: "achievement", unlock_condition: %{"description" => "Complete security audit"}, nodes_cost: 0},
    %{slug: "content-creator", name: "Content Creator", description: "Created 50 original posts with high engagement.", icon_url: "/images/badges/content-creator.png", rarity: "epic", category: "competitive", track: "content", unlock_type: "achievement", unlock_condition: %{"description" => "50 original posts with high engagement"}, nodes_cost: 0},
    %{slug: "moderator-star", name: "Moderator Star", description: "Moderated the community for 30 days.", icon_url: "/images/badges/moderator-star.png", rarity: "epic", category: "social", track: "moderation", unlock_type: "achievement", unlock_condition: %{"description" => "Moderate for 30 days"}, nodes_cost: 0},

    # ─── LEGENDARY (6) ───
    %{slug: "og-member", name: "OG Member", description: "Account older than 1 year.", icon_url: "/images/badges/og-member.png", rarity: "legendary", category: "social", track: "tenure", unlock_type: "achievement", unlock_condition: %{"description" => "Account older than 1 year"}, nodes_cost: 0},
    %{slug: "forum-elder", name: "Forum Elder", description: "Posted 1000 forum messages.", icon_url: "/images/badges/forum-elder.png", rarity: "legendary", category: "competitive", track: "forums", unlock_type: "achievement", unlock_condition: %{"description" => "1000 forum posts"}, nodes_cost: 0},
    %{slug: "streak-immortal", name: "Streak Immortal", description: "Maintained a 365-day login streak.", icon_url: "/images/badges/streak-immortal.png", rarity: "legendary", category: "social", track: "activity", unlock_type: "achievement", unlock_condition: %{"description" => "365-day login streak"}, nodes_cost: 0},
    %{slug: "community-legend", name: "Community Legend", description: "500 friends and high reputation.", icon_url: "/images/badges/community-legend.png", rarity: "legendary", category: "social", track: "social", unlock_type: "achievement", unlock_condition: %{"description" => "500 friends and high reputation"}, nodes_cost: 0},
    %{slug: "grand-moderator", name: "Grand Moderator", description: "Moderated for 1 year.", icon_url: "/images/badges/grand-moderator.png", rarity: "legendary", category: "social", track: "moderation", unlock_type: "achievement", unlock_condition: %{"description" => "Moderate for 1 year"}, nodes_cost: 0},
    %{slug: "platform-guardian", name: "Platform Guardian", description: "Exceptional contributions to the platform.", icon_url: "/images/badges/platform-guardian.png", rarity: "legendary", category: "social", track: "contribution", unlock_type: "achievement", unlock_condition: %{"description" => "Exceptional platform contribution"}, nodes_cost: 0},

    # ─── MYTHIC (4) ───
    %{slug: "transcendent", name: "Transcendent", description: "Reached maximum prestige level.", icon_url: "/images/badges/transcendent.png", rarity: "mythic", category: "special", track: "prestige", unlock_type: "achievement", unlock_condition: %{"description" => "Reach maximum prestige"}, nodes_cost: 0},
    %{slug: "founder", name: "Founder", description: "A founding member of the platform.", icon_url: "/images/badges/founder.png", rarity: "mythic", category: "special", track: "tenure", unlock_type: "achievement", unlock_condition: %{"description" => "Founding member status"}, nodes_cost: 0},
    %{slug: "mythic-contributor", name: "Mythic Contributor", description: "Legendary contributions to the platform.", icon_url: "/images/badges/mythic-contributor.png", rarity: "mythic", category: "special", track: "contribution", unlock_type: "achievement", unlock_condition: %{"description" => "Legendary contributions to platform"}, nodes_cost: 0},
    %{slug: "the-one", name: "The One", description: "Completed every single achievement.", icon_url: "/images/badges/the-one.png", rarity: "mythic", category: "special", track: "special", unlock_type: "achievement", unlock_condition: %{"description" => "Complete all other achievements"}, nodes_cost: 0}
  ]
  |> Enum.with_index(1)
  |> Enum.map(fn {badge, idx} ->
    Map.merge(badge, %{
      id: Ecto.UUID.generate(),
      stackable: false,
      sort_order: idx,
      is_active: true,
      inserted_at: now,
      updated_at: now
    })
  end)

{count, _} = Repo.insert_all("badges", badges, on_conflict: :nothing, conflict_target: :slug)
IO.puts("✓ Seeded #{count}/#{length(badges)} badges (on_conflict: :nothing)")
