# Script: Seed all 42 canonical Lottie avatar borders
#
# Upserts into the avatar_borders table — safe to run on top of existing data.
# Matches slug as the conflict key (unique index on slug WHERE deactivated_at IS NULL).
#
# Usage:
#   mix run priv/repo/seeds/seed_borders.exs
#
# All borders use Lottie animations. The lottie_url points to the static JSON
# file served from /lottie/borders/ on the web app CDN.

alias Cgraph.Repo

borders = [
  # ─── FREE (4) ───
  %{
    slug: "border-8bit-free-01",
    name: "Pixel Ring",
    description: "A retro pixel-art ring in classic green.",
    theme: "8bit",
    rarity: "free",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/8bit_free_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 1,
    is_active: true,
    metadata: %{"primaryColor" => "#00ff41", "tags" => ["8bit", "retro", "free", "pixel"]}
  },
  %{
    slug: "border-kawaii-free-01",
    name: "Pastel Circle",
    description: "A dreamy pastel ring with soft pink tones.",
    theme: "kawaii",
    rarity: "free",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/kawaii_free_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 2,
    is_active: true,
    metadata: %{"primaryColor" => "#ffb3d9", "tags" => ["kawaii", "cute", "free", "pastel"]}
  },
  %{
    slug: "border-elemental-water-free-01",
    name: "Calm Ripple",
    description: "A serene water-blue ring evoking gentle ripples.",
    theme: "elemental",
    rarity: "free",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/elemental_water_free_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 3,
    is_active: true,
    metadata: %{"primaryColor" => "#006994", "tags" => ["water", "elemental", "free", "calm"]}
  },
  %{
    slug: "border-gothic-free-01",
    name: "Iron Band",
    description: "A dark iron ring with a gothic edge.",
    theme: "gothic",
    rarity: "free",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/gothic_free_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 4,
    is_active: true,
    metadata: %{"primaryColor" => "#6b21a8", "tags" => ["gothic", "dark", "free", "iron"]}
  },

  # ─── COMMON (8) ───
  %{
    slug: "border-anime-common-01",
    name: "Soft Glow",
    description: "A gentle anime-style glow with warm pink hues.",
    theme: "anime",
    rarity: "common",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/anime_common_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 5,
    is_active: true,
    metadata: %{"primaryColor" => "#ff6b9d", "tags" => ["anime", "glow", "common", "soft"]}
  },
  %{
    slug: "border-cyberpunk-common-01",
    name: "Neon Trace",
    description: "A subtle neon outline pulsing with cyber energy.",
    theme: "cyberpunk",
    rarity: "common",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/cyberpunk_common_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 6,
    is_active: true,
    metadata: %{"primaryColor" => "#00f5ff", "tags" => ["cyberpunk", "neon", "common", "trace"]}
  },
  %{
    slug: "border-japanese-common-01",
    name: "Ink Stroke",
    description: "A traditional ink brush stroke ring.",
    theme: "japanese",
    rarity: "common",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/japanese_common_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 7,
    is_active: true,
    metadata: %{"primaryColor" => "#e8105f", "tags" => ["japanese", "traditional", "common", "ink"]}
  },
  %{
    slug: "border-elemental-fire-common-01",
    name: "Warm Ember",
    description: "A warm ember ring glowing with subtle orange.",
    theme: "elemental",
    rarity: "common",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/elemental_fire_common_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 8,
    is_active: true,
    metadata: %{"primaryColor" => "#ff4500", "tags" => ["fire", "elemental", "common", "ember"]}
  },
  %{
    slug: "border-elemental-earth-common-01",
    name: "Moss Ring",
    description: "An earthy ring with forest-green tones.",
    theme: "elemental",
    rarity: "common",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/elemental_earth_common_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 9,
    is_active: true,
    metadata: %{"primaryColor" => "#3d2b1f", "tags" => ["earth", "elemental", "common", "nature"]}
  },
  %{
    slug: "border-elemental-air-common-01",
    name: "Breeze Halo",
    description: "A light, airy halo in soft sky tones.",
    theme: "elemental",
    rarity: "common",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/elemental_air_common_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 10,
    is_active: true,
    metadata: %{"primaryColor" => "#e0f7ff", "tags" => ["air", "elemental", "common", "breeze"]}
  },
  %{
    slug: "border-cosmic-common-01",
    name: "Starlight Band",
    description: "A cosmic ring speckled with distant starlight.",
    theme: "cosmic",
    rarity: "common",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/cosmic_common_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 11,
    is_active: true,
    metadata: %{"primaryColor" => "#0d0d2b", "tags" => ["cosmic", "space", "common", "stars"]}
  },
  %{
    slug: "border-gothic-common-01",
    name: "Silver Chain",
    description: "A delicate silver chain encircling the avatar.",
    theme: "gothic",
    rarity: "common",
    tier: 1,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1},
    lottie_url: "/lottie/borders/gothic_common_01.json",
    lottie_config: %{"loop" => true, "speed" => 1},
    unlock_type: "default",
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 12,
    is_active: true,
    metadata: %{"primaryColor" => "#6b21a8", "tags" => ["gothic", "silver", "common", "chain"]}
  },

  # ─── RARE (10) ───
  %{
    slug: "border-8bit-rare-01",
    name: "Retro Spinner",
    description: "A dashed retro ring spinning at a steady pace.",
    theme: "8bit",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/8bit_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 5, "description" => "Reach Level 5"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 13,
    is_active: true,
    metadata: %{"primaryColor" => "#00ff41", "tags" => ["8bit", "retro", "rare", "spinning"]}
  },
  %{
    slug: "border-anime-rare-01",
    name: "Sakura Drift",
    description: "A softly rotating anime ring with sakura essence.",
    theme: "anime",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/anime_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 8, "description" => "Reach Level 8"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 14,
    is_active: true,
    metadata: %{"primaryColor" => "#ff6b9d", "tags" => ["anime", "sakura", "rare", "drifting"]}
  },
  %{
    slug: "border-cyberpunk-rare-01",
    name: "Circuit Loop",
    description: "A spinning circuit-board loop in electric cyan.",
    theme: "cyberpunk",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/cyberpunk_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 10, "description" => "Reach Level 10"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 15,
    is_active: true,
    metadata: %{"primaryColor" => "#00f5ff", "tags" => ["cyberpunk", "circuit", "rare", "loop"]}
  },
  %{
    slug: "border-japanese-rare-01",
    name: "Torii Gate",
    description: "A rotating ring inspired by sacred torii arches.",
    theme: "japanese",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/japanese_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 12, "description" => "Reach Level 12"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 16,
    is_active: true,
    metadata: %{"primaryColor" => "#e8105f", "tags" => ["japanese", "torii", "rare", "traditional"]}
  },
  %{
    slug: "border-gothic-rare-01",
    name: "Crimson Thorn",
    description: "A rotating gothic ring tinged with crimson.",
    theme: "gothic",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/gothic_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 15, "description" => "Reach Level 15"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 17,
    is_active: true,
    metadata: %{"primaryColor" => "#6b21a8", "tags" => ["gothic", "crimson", "rare", "thorns"]}
  },
  %{
    slug: "border-kawaii-rare-01",
    name: "Rainbow Ribbon",
    description: "A cheerful rotating rainbow ribbon ring.",
    theme: "kawaii",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/kawaii_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 18, "description" => "Reach Level 18"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 18,
    is_active: true,
    metadata: %{"primaryColor" => "#ffb3d9", "tags" => ["kawaii", "rainbow", "rare", "ribbon"]}
  },
  %{
    slug: "border-elemental-fire-rare-01",
    name: "Flame Wheel",
    description: "A spinning ring of flickering flame.",
    theme: "elemental",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/elemental_fire_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 20, "description" => "Reach Level 20"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 19,
    is_active: true,
    metadata: %{"primaryColor" => "#ff4500", "tags" => ["fire", "elemental", "rare", "flame"]}
  },
  %{
    slug: "border-elemental-water-rare-01",
    name: "Tide Ring",
    description: "A gently rotating tidal ring in ocean blue.",
    theme: "elemental",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/elemental_water_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 22, "description" => "Reach Level 22"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 20,
    is_active: true,
    metadata: %{"primaryColor" => "#006994", "tags" => ["water", "elemental", "rare", "tide"]}
  },
  %{
    slug: "border-elemental-earth-rare-01",
    name: "Root Braid",
    description: "A slowly spinning ring of braided roots.",
    theme: "elemental",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/elemental_earth_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 25, "description" => "Reach Level 25"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 21,
    is_active: true,
    metadata: %{"primaryColor" => "#3d2b1f", "tags" => ["earth", "elemental", "rare", "roots"]}
  },
  %{
    slug: "border-cosmic-rare-01",
    name: "Nebula Arc",
    description: "A rotating arc of cosmic nebula colors.",
    theme: "cosmic",
    rarity: "rare",
    tier: 3,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.6},
    lottie_url: "/lottie/borders/cosmic_rare_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.6},
    unlock_type: "level",
    unlock_requirement: %{"type" => "level", "value" => 28, "description" => "Reach Level 28"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 22,
    is_active: true,
    metadata: %{"primaryColor" => "#0d0d2b", "tags" => ["cosmic", "nebula", "rare", "space"]}
  },

  # ─── EPIC (8) ───
  %{
    slug: "border-8bit-epic-01",
    name: "Glitch Frame",
    description: "Dual counter-rotating rings with a glitchy 8-bit pulse.",
    theme: "8bit",
    rarity: "epic",
    tier: 4,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.8},
    lottie_url: "/lottie/borders/8bit_epic_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.8},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "retro_master", "description" => "Unlock the Retro Master achievement"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 23,
    is_active: true,
    metadata: %{"primaryColor" => "#00ff41", "tags" => ["8bit", "glitch", "epic", "retro"]}
  },
  %{
    slug: "border-anime-epic-01",
    name: "Spirit Flame",
    description: "Dual spinning anime rings with spiritual fire energy.",
    theme: "anime",
    rarity: "epic",
    tier: 4,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.8},
    lottie_url: "/lottie/borders/anime_epic_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.8},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "anime_fan", "description" => "Unlock the Anime Fan achievement"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 24,
    is_active: true,
    metadata: %{"primaryColor" => "#ff6b9d", "tags" => ["anime", "spirit", "epic", "flame"]}
  },
  %{
    slug: "border-cyberpunk-epic-01",
    name: "Holo Grid",
    description: "Counter-rotating holographic rings pulsing with data.",
    theme: "cyberpunk",
    rarity: "epic",
    tier: 4,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.8},
    lottie_url: "/lottie/borders/cyberpunk_epic_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.8},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "cyber_explorer", "description" => "Unlock the Cyber Explorer achievement"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 25,
    is_active: true,
    metadata: %{"primaryColor" => "#00f5ff", "tags" => ["cyberpunk", "holo", "epic", "grid"]}
  },
  %{
    slug: "border-japanese-epic-01",
    name: "Dragon Scale",
    description: "Dual rings with shimmering dragon scale patterns.",
    theme: "japanese",
    rarity: "epic",
    tier: 4,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.8},
    lottie_url: "/lottie/borders/japanese_epic_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.8},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "dragon_warrior", "description" => "Unlock the Dragon Warrior achievement"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 26,
    is_active: true,
    metadata: %{"primaryColor" => "#e8105f", "tags" => ["japanese", "dragon", "epic", "scale"]}
  },
  %{
    slug: "border-kawaii-epic-01",
    name: "Sugar Rush",
    description: "Sweet dual rings spinning with candy-colored energy.",
    theme: "kawaii",
    rarity: "epic",
    tier: 4,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.8},
    lottie_url: "/lottie/borders/kawaii_epic_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.8},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "sweet_tooth", "description" => "Unlock the Sweet Tooth achievement"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 27,
    is_active: true,
    metadata: %{"primaryColor" => "#ffb3d9", "tags" => ["kawaii", "sugar", "epic", "candy"]}
  },
  %{
    slug: "border-elemental-fire-epic-01",
    name: "Inferno Ring",
    description: "Blazing dual rings of intense fire and molten gold.",
    theme: "elemental",
    rarity: "epic",
    tier: 4,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.8},
    lottie_url: "/lottie/borders/elemental_fire_epic_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.8},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "fire_master", "description" => "Master the Elemental Fire challenges"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 28,
    is_active: true,
    metadata: %{"primaryColor" => "#ff4500", "tags" => ["fire", "elemental", "epic", "inferno"]}
  },
  %{
    slug: "border-elemental-air-epic-01",
    name: "Storm Vortex",
    description: "Swirling dual rings of wind and lightning.",
    theme: "elemental",
    rarity: "epic",
    tier: 4,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.8},
    lottie_url: "/lottie/borders/elemental_air_epic_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.8},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "storm_chaser", "description" => "Chase 10 elemental storms"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 29,
    is_active: true,
    metadata: %{"primaryColor" => "#e0f7ff", "tags" => ["air", "elemental", "epic", "storm"]}
  },
  %{
    slug: "border-cosmic-epic-01",
    name: "Void Gate",
    description: "Counter-rotating cosmic rings opening a void gate.",
    theme: "cosmic",
    rarity: "epic",
    tier: 4,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 0.8},
    lottie_url: "/lottie/borders/cosmic_epic_01.json",
    lottie_config: %{"loop" => true, "speed" => 0.8},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "void_walker", "description" => "Walk through the cosmic void"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: true,
    sort_order: 30,
    is_active: true,
    metadata: %{"primaryColor" => "#0d0d2b", "tags" => ["cosmic", "void", "epic", "gate"]}
  },

  # ─── LEGENDARY (8) ───
  %{
    slug: "border-8bit-legendary-01",
    name: "Arcade Champion",
    description: "Triple rotating rings with orbiting pixel orbs.",
    theme: "8bit",
    rarity: "legendary",
    tier: 6,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.0},
    lottie_url: "/lottie/borders/8bit_legendary_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.0},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "arcade_champion", "description" => "Become the Arcade Champion"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 31,
    is_active: true,
    metadata: %{"primaryColor" => "#00ff41", "particleCount" => 8, "tags" => ["8bit", "champion", "legendary", "arcade"]}
  },
  %{
    slug: "border-anime-legendary-01",
    name: "Super Saiyan",
    description: "Triple energy rings with sparking power aura.",
    theme: "anime",
    rarity: "legendary",
    tier: 6,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.0},
    lottie_url: "/lottie/borders/anime_legendary_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.0},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "power_unleashed", "description" => "Unleash your true power"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 32,
    is_active: true,
    metadata: %{"primaryColor" => "#ff6b9d", "particleCount" => 8, "tags" => ["anime", "saiyan", "legendary", "power"]}
  },
  %{
    slug: "border-cyberpunk-legendary-01",
    name: "Netrunner",
    description: "Triple data rings with diamond-shaped data packets.",
    theme: "cyberpunk",
    rarity: "legendary",
    tier: 6,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.0},
    lottie_url: "/lottie/borders/cyberpunk_legendary_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.0},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "netrunner_elite", "description" => "Reach Netrunner Elite status"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 33,
    is_active: true,
    metadata: %{"primaryColor" => "#00f5ff", "particleCount" => 8, "tags" => ["cyberpunk", "netrunner", "legendary", "data"]}
  },
  %{
    slug: "border-japanese-legendary-01",
    name: "Shogun Crest",
    description: "Ornate triple rings with orbiting spirit orbs.",
    theme: "japanese",
    rarity: "legendary",
    tier: 6,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.0},
    lottie_url: "/lottie/borders/japanese_legendary_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.0},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "shogun_rank", "description" => "Attain Shogun rank"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 34,
    is_active: true,
    metadata: %{"primaryColor" => "#e8105f", "particleCount" => 8, "tags" => ["japanese", "shogun", "legendary", "crest"]}
  },
  %{
    slug: "border-gothic-legendary-01",
    name: "Blood Moon",
    description: "Dark triple rings with sparking crimson energy.",
    theme: "gothic",
    rarity: "legendary",
    tier: 6,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.0},
    lottie_url: "/lottie/borders/gothic_legendary_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.0},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "blood_moon", "description" => "Witness the Blood Moon event"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 35,
    is_active: true,
    metadata: %{"primaryColor" => "#dc143c", "particleCount" => 8, "tags" => ["gothic", "blood", "legendary", "moon"]}
  },
  %{
    slug: "border-elemental-water-legendary-01",
    name: "Maelstrom",
    description: "Triple ocean rings with swirling water orbs.",
    theme: "elemental",
    rarity: "legendary",
    tier: 6,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.0},
    lottie_url: "/lottie/borders/elemental_water_legendary_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.0},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "ocean_master", "description" => "Master the Ocean depths"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 36,
    is_active: true,
    metadata: %{"primaryColor" => "#006994", "particleCount" => 8, "tags" => ["water", "elemental", "legendary", "maelstrom"]}
  },
  %{
    slug: "border-elemental-earth-legendary-01",
    name: "World Tree",
    description: "Triple root rings with floating diamond crystals.",
    theme: "elemental",
    rarity: "legendary",
    tier: 6,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.0},
    lottie_url: "/lottie/borders/elemental_earth_legendary_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.0},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "world_tree", "description" => "Grow the World Tree"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 37,
    is_active: true,
    metadata: %{"primaryColor" => "#3d2b1f", "particleCount" => 8, "tags" => ["earth", "elemental", "legendary", "tree"]}
  },
  %{
    slug: "border-cosmic-legendary-01",
    name: "Supernova",
    description: "Triple cosmic rings with sparking stellar energy.",
    theme: "cosmic",
    rarity: "legendary",
    tier: 6,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.0},
    lottie_url: "/lottie/borders/cosmic_legendary_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.0},
    unlock_type: "achievement",
    unlock_requirement: %{"type" => "achievement", "value" => "supernova", "description" => "Trigger a Supernova event"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 38,
    is_active: true,
    metadata: %{"primaryColor" => "#4b0082", "particleCount" => 8, "tags" => ["cosmic", "supernova", "legendary", "stellar"]}
  },

  # ─── MYTHIC (4) ───
  %{
    slug: "border-cyberpunk-mythic-01",
    name: "Digital Ascension",
    description: "Reality-warping neon rings with 16 hex particles and bloom.",
    theme: "cyberpunk",
    rarity: "mythic",
    tier: 8,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.3},
    lottie_url: "/lottie/borders/cyberpunk_mythic_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.3},
    unlock_type: "event",
    unlock_requirement: %{"type" => "event", "value" => "digital_ascension", "description" => "Witness the Digital Ascension"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 39,
    is_active: true,
    metadata: %{"primaryColor" => "#00f5ff", "particleCount" => 16, "tags" => ["cyberpunk", "ascension", "mythic", "digital"]}
  },
  %{
    slug: "border-cosmic-mythic-01",
    name: "Event Horizon",
    description: "Reality-warping cosmic rings with 16 diamond particles and bloom.",
    theme: "cosmic",
    rarity: "mythic",
    tier: 8,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.3},
    lottie_url: "/lottie/borders/cosmic_mythic_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.3},
    unlock_type: "event",
    unlock_requirement: %{"type" => "event", "value" => "event_horizon", "description" => "Survive the Event Horizon"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 40,
    is_active: true,
    metadata: %{"primaryColor" => "#0d0d2b", "particleCount" => 16, "tags" => ["cosmic", "horizon", "mythic", "event"]}
  },
  %{
    slug: "border-elemental-fire-mythic-01",
    name: "Phoenix Rebirth",
    description: "Blazing phoenix rings with 16 fire sparks and brilliant bloom.",
    theme: "elemental",
    rarity: "mythic",
    tier: 8,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.3},
    lottie_url: "/lottie/borders/elemental_fire_mythic_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.3},
    unlock_type: "event",
    unlock_requirement: %{"type" => "event", "value" => "phoenix_rebirth", "description" => "Witness the Phoenix Rebirth"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 41,
    is_active: true,
    metadata: %{"primaryColor" => "#ff4500", "particleCount" => 16, "tags" => ["fire", "elemental", "mythic", "phoenix"]}
  },
  %{
    slug: "border-anime-mythic-01",
    name: "Kami Mode",
    description: "Divine anime rings with 16 diamond particles and celestial bloom.",
    theme: "anime",
    rarity: "mythic",
    tier: 8,
    border_style: %{"style" => "lottie"},
    animation_type: "lottie",
    animation_config: %{"loop" => true, "speed" => 1.3},
    lottie_url: "/lottie/borders/anime_mythic_01.json",
    lottie_config: %{"loop" => true, "speed" => 1.3},
    unlock_type: "event",
    unlock_requirement: %{"type" => "event", "value" => "kami_mode", "description" => "Unlock Kami Mode"},
    coin_cost: 0,
    is_purchasable: false,
    is_tradeable: false,
    sort_order: 42,
    is_active: true,
    metadata: %{"primaryColor" => "#ff6b9d", "particleCount" => 16, "tags" => ["anime", "kami", "mythic", "divine"]}
  }
]

now = DateTime.utc_now() |> DateTime.truncate(:second)

Enum.each(borders, fn border ->
  # Build the column/value lists for the upsert
  slug = border.slug
  values = Map.merge(border, %{inserted_at: now, updated_at: now})
  |> Map.drop([:slug])

  # Upsert: insert or update by slug
  Repo.query!(
    """
    INSERT INTO avatar_borders (
      id, slug, name, description, theme, rarity, tier,
      border_style, animation_type, animation_config,
      particle_config, glow_config,
      lottie_url, lottie_config,
      unlock_type, unlock_requirement, coin_cost,
      is_purchasable, is_tradeable, sort_order, is_active,
      metadata, inserted_at, updated_at
    ) VALUES (
      gen_random_uuid(), $1, $2, $3, $4, $5, $6,
      $7, $8, $9,
      '{}'::jsonb, '{}'::jsonb,
      $10, $11,
      $12, $13, $14,
      $15, $16, $17, $18,
      $19, $20, $21
    )
    ON CONFLICT (slug) WHERE deactivated_at IS NULL
    DO UPDATE SET
      name = EXCLUDED.name,
      description = EXCLUDED.description,
      theme = EXCLUDED.theme,
      rarity = EXCLUDED.rarity,
      tier = EXCLUDED.tier,
      border_style = EXCLUDED.border_style,
      animation_type = EXCLUDED.animation_type,
      animation_config = EXCLUDED.animation_config,
      lottie_url = EXCLUDED.lottie_url,
      lottie_config = EXCLUDED.lottie_config,
      unlock_type = EXCLUDED.unlock_type,
      unlock_requirement = EXCLUDED.unlock_requirement,
      coin_cost = EXCLUDED.coin_cost,
      is_purchasable = EXCLUDED.is_purchasable,
      is_tradeable = EXCLUDED.is_tradeable,
      sort_order = EXCLUDED.sort_order,
      is_active = EXCLUDED.is_active,
      metadata = EXCLUDED.metadata,
      updated_at = EXCLUDED.updated_at
    """,
    [
      slug,
      values.name,
      values.description,
      values.theme,
      values.rarity,
      values.tier,
      values.border_style,
      values.animation_type,
      values.animation_config,
      values.lottie_url,
      values.lottie_config,
      values.unlock_type,
      Map.get(values, :unlock_requirement, %{}),
      values.coin_cost,
      values.is_purchasable,
      values.is_tradeable,
      values.sort_order,
      values.is_active,
      values.metadata,
      values.inserted_at,
      values.updated_at
    ]
  )
end)

IO.puts("✓ Seeded #{length(borders)} Lottie avatar borders (upsert)")
